### ISSUE TITLE
Update steps copy to standardize casing

### ISSUE THREAD

**Issue by raiseandfall** [blockchain-certificates/cert-verifier-js#118]
Make sure all steps labels are capitalized: https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/data/i18n.json

**Comment by lemoustachiste** [comment]
better to use CSS no?
At least if we need to revert it's only one rule

**Comment by raiseandfall** [comment]
Definitely. I think it's up to the consumer at this point, but I'd like to have the same casing here for consistency, so maybe just first letter of the translation entry capitalize, and the rest lowercase ?

**Comment by guix77** [comment]
Duplicating / merging with https://github.com/blockchain-certificates/cert-verifier-js/issues/114, no?
