### ISSUE TITLE
Foreign languages not being displayed

### ISSUE THREAD

**Issue by akodate** [blockchain-certificates/cert-verifier-js#145]
**Describe the bug**

blockcerts-verifier doesn't seem to display foreign languages.

**To Reproduce**

Set browser language to Italian or Japanese in the latest version of Firefox (66.0.4)

**Expected behavior**

I expected to see the i18n translations on the progress bar.

**Screenshots**

<img width="924" alt="Screen Shot 2019-05-07 at 5 05 15 AM" src="https://user-images.githubusercontent.com/6196694/57287538-bd46b600-7085-11e9-8797-5564e5fe9b73.png">

**Environment information:**
N/A

**Additional context**

I hope I didn't miss something obvious. Please assist me with some guidance if you can.

**Comment by lemoustachiste** [comment]
Hi @akodate, 

thanks for reporting this issue. I am not the most familiar with this code, but I have found this which should be of interest:
https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/constants/verificationSubSteps.js#L18

It seems that as we are generating substeps terms to be consumed by any client (namely blockcerts-verifier), that we only use the english version.

Similarly we should probably handle translations for this parent steps: https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/constants/verificationSteps.js#L6

Although I would like to have @raiseandfall input to have a determinate opinion here, it seems that this should be where to work from.

**Comment by akodate** [comment]
Thanks so much for the swift response @lemoustachiste 

It may not seem like much, but I've been told by some non-native English speakers (Japanese people in particular) that displaying these things in their language would make a big difference for them in terms of usability. Translations in several languages are already available, so I think it would be great to be able to use them.

**Comment by lemoustachiste** [comment]
That makes sense @akodate,

I think what we are going to try and do is the following:
- you can set the language by a parameter as currently https://github.com/blockchain-certificates/cert-verifier-js#parameter
- then use the browser language
- if translations are not available fallback to english.

Do you think that would be acceptable? We would still face the issue that if someone sets the language manually, that wouldn't translate and some people might be excluded, but I think for compatibility reasons we can't just drop that feature.

**Comment by akodate** [comment]
Yes @lemoustachiste that sounds like a good approach!

There are fallback languages on many browsers as well; perhaps we can fall back through them first since I don't think the cert locale setting is very well-known (and the inspector of the certificate might speak a different language than the holder).

**Comment by raiseandfall** [comment]
@akodate thank you for reporting this. This is how we detect the browser / host locale right now: https://github.com/blockchain-certificates/cert-verifier-js/blob/277bd1f3aeb5fac1c784bd668e9f087f8f02ae27/src/certificate.js#L69

- if the parameter is `'auto'`, it tries to detect the locale
- if not `'auto'` it uses the locale set as a parameter
- it checks out the locals is supported in the i18n files and defaults to English if not

There might be a problem on detecting the locale in your case. I can test later today.

**Comment by akodate** [comment]
Hi @raiseandfall I just wanted to see if you've had a chance to test this yet.
I've verified some sample certificates on blockcerts.org (as well as the latest version of blockcerts-verifier on my own site) with Firefox set to Spanish as well as Italian and Japanese and I'm still only getting English (not sure about Chrome and Safari).

**Comment by lemoustachiste** [comment]
@akodate I just spent some time testing. Italian worked fine, but indeed I didn't get japanese working. I'll investigate more.

**Comment by raiseandfall** [comment]
@akodate I didn't have time to test yet. The first thing I see is that `blockcerts-verifier` is still using `v2.2.0`, while japanese was introduced in `v2.3.0` so we need to bump the version there first.
@lemoustachiste is on it, thanks for taking care of it!

**Comment by lemoustachiste** [comment]
@akodate it is all good now

this is on blockcerts.org
<img width="681" alt="Screenshot 2019-05-10 at 18 53 06" src="https://user-images.githubusercontent.com/12797962/57543546-f5cfe380-7354-11e9-866a-87ae562489d7.png">

However we noticed the last step is hard coded into the blockcerts verifier, and cert-verifier-js does not communicate the step. So we will have to work on that before it supports full translation of the verification process.

**Comment by akodate** [comment]
I've tested on my end and everything looks great! Thanks so much for addressing this @lemoustachiste and @raiseandfall 

If you'll let me know when full translation is supported, I'll contribute JP translations and upgrade my blockcerts-verifier again.

**Comment by raiseandfall** [comment]
@akodate Will do! Thank you again for contributing!
