### ISSUE TITLE
Computed hash does not match remote hash

### ISSUE THREAD

**Issue by ssho0508** [blockchain-certificates/cert-verifier-js#1496]
I created a VC by cert-issuer and I tried to verified it by the blockcert-verifier. In the demo/explorer-api-overwrite-default.html, I pase the explorerAPI like this:
```
          const explorerAPI = {
            key:'',
            keyPropertyName:'',
            serviceURL:`https://localhost:443/api?module=transaction&action=gettxinfo&txhash={transaction_id}`,
            priority: 0,
            parsingFunction: function (jsonRespons) {
              const data = jsonRespons.jsonResponse.result
              // const remoteHash = data.input
              const remoteHash = `d8911bbcdb2e16253e66b18adb86ec3f2658cc93c6c98add51eb1098f3352f65`;

              // const issuingAddress = `0xed9d02e382b34818e88b88a309c7fe71e65f419d`;
              const issuingAddress = data.from;

              const time= new Date(parseInt(data.timeStamp) * 1000);
              const revokedAddresses = []

              return {
                remoteHash,
                issuingAddress,
                time,
                revokedAddresses
              };
            }
          };
````
The remoteHash is took from the cert-issuer's output and it can be identified by the explorer's transaction response.
I met the error "Computed hash does not match remote hash" so that I tried to print the local hash.
How can I print or log the local hash so that I can know where I make wrong with the verifier?
(ps: I also tried to use the tests to calculate the local hash but still met some troubles with the jsonld version.)
**To Reproduce**
1. use cert-issuer to issue a VC
2. rewrite the demo/explorer-api-overwrite-default.html of blockcert-verifier
3. verify

**Environment information:**
 - Node version: node v18.16.0 lts  
 -    npm 9.6.7
 - OS: wsl ubuntu 22.04.2 lts
 - blockcerts-verifier 1.56.0
 - cert-issuer 3.5.0

**Additional context**
Here is transaction response
```
{
    "message": "OK",
    "result": {
        "blockNumber": "4800",
        "confirmations": "955",
        "from": "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
        "gasLimit": "25000",
        "gasPrice": "0",
        "gasUsed": "21512",
        "hash": "0xcc4b48ed64a680d91f98604956ec5f1dd30ceda7087cf9dc0ed4dfd61f61999f",
        "input": "0xd8911bbcdb2e16253e66b18adb86ec3f2658cc93c6c98add51eb1098f3352f65",
        "logs": [],
        "next_page_params": null,
        "revertReason": "",
        "success": true,
        "timeStamp": "1688022846",
        "to": "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddead",
        "value": "0"
    },
    "status": "1"
}
```

**Comment by lemoustachiste** [comment]
HI @ssho0508,

I'm not sure I can exactly replicate the issue as it seems related to your data. This is where the hash is computed for the verifier:  https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/inspectors/computeLocalHash.ts

You may want to see what's actually normalized by jsonld on the issuer and on the verifier side, as this will likely give you more insights as to what the potential issue can be.

**Comment by lemoustachiste** [comment]
Also at this moment this package is made to work with node 16. I'm in the process of upgrading a few things and make sure it works with node 18 but I'm not 100% it works as expected at this time.

**Comment by ssho0508** [comment]
Thanks for the reply!
I will try to use the node 16 to debug and I think maybe I make something wrong when I used the cert-tool to make a unsigned-credential. I found that the computeLocalHash is using the `@context` to hash. and I'm not sure whether I make wrong with adding custom fields. Forgive my stupid.
```{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        {
            "test": {
                "@id": "schema:description"
            },
            "alumniOf": {
                "@id": "schema:description"
            },
            "evidence": {
                "@id": "schema:description"
            },
            "nonce": {
                "@id": "schema:description"
            }
        },
        "https://w3id.org/blockcerts/v3"
    ],
    "type": [
        "VerifiableCredential",
        "BlockcertsCredential"
    ],
    "issuer": "http://localhost:7000/profile",
    "issuanceDate": "2023-07-03T01:53:06Z",
    "id": "urn:uuid:0e2c5a42-a400-4042-864f-08cd064760d4",
    "credentialSubject": {
        "id": "ecdsa-koblitz-pubkey:mkwntSiQmc14H65YxwckLenxY3DsEpvFbe",
        "alumniOf": {
            "id": "http://localhost:7000/profile"
        },
        "evidence": "test M"
    },
    "nonce": "kim custom subtitle",
    "test": "mg"
}

**Comment by lemoustachiste** [comment]
I don't think you are stupid, jsonld is not too straightforward.

If you are going to redefine some terms, I suggest you try with the JSONLD playground: https://fhircat.org/jsonld/playground/, that way you can try and adjust your definitions so that they are correclty picked up.

However both the issuer and the verifier should normalize the document the same way before hashing so I'm not entirely sure the problem is laying around your context definition.

**Comment by lemoustachiste** [comment]
You'll want to print this: https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/inspectors/computeLocalHash.ts#L52

And this: https://github.com/blockchain-certificates/cert-issuer/blob/master/cert_issuer/normalization_handler.py#L12

**Comment by ssho0508** [comment]
That's exactly what I need!
I found that it's because the `"evidence": "test M"` can not be hashed by cert-issuer and it can be hashed by cert-verifier-js.
Anyway, I make it by moving the `"evidence": "test M"` outside or just drop it.
Thank you for you help!

**Comment by lemoustachiste** [comment]
Ok I think I need to investigate  why there is a difference in normalization in cert-issuer

**Comment by ssho0508** [comment]
Sorry to bother you again.
I found the "evidence" has been defined in "https://www.w3.org/2018/credentials/v1" and that's what make the difference.
I change it to other names like testCredential and the hashes of both sides are the same.
So the normalization is different, but there is a way to avoid it.
Thank you!
