### ISSUE TITLE
eth sepolia verification failed

### ISSUE THREAD

**Issue by wantaekchoi** [blockchain-certificates/cert-verifier-js#1541]
**Describe the bug**

Verification of my blockcert v2 badges issued on Ethereum Sepolia fails.

- Etherscan: Ok, Blockcypher: Fail

I've tried to use the custom explorerAPIs option, but I can't overwrite the default explorerAPIs. 

Am I missing something? Can someone please help me?

**To Reproduce**

1. `const cert = new Certification(myCertJsonString)`
1. `cert.init()` // ok
1. `cert.verify()` // Verification error occurs: {"error": "Transaction 5d780052bf004d1f46ab857f7ac5c703b0544fca0863e0022affe72561e886d6 not found."}

**Expected behavior**

Etherscan-Sepolia is OK (it retrieves the transaction data successfully).

- https://api-sepolia.etherscan.io/api?module=proxy&action=eth_getTransactionByHash&txhash=0x5d780052bf004d1f46ab857f7ac5c703b0544fca0863e0022affe72561e886d6

Blockcypher-btest is Fail (404 not found, I assumed they use their own testnet, not Sepolia).

- https://api.blockcypher.com/v1/beth/test/txs/0x5d780052bf004d1f46ab857f7ac5c703b0544fca0863e0022affe72561e886d6?limit=500

Is it correct behavior to request cross-verification on different blockchains?

Or am I doing something wrong?

**Screenshots**

![image](https://github.com/blockchain-certificates/cert-verifier-js/assets/78516163/a844ccb8-4cc3-4855-bbc0-38fca7f17a1f)
![image](https://github.com/blockchain-certificates/cert-verifier-js/assets/78516163/71f5619c-c9e5-4954-a7d3-a23f7464aaee)
<img width="664" alt="image" src="https://github.com/blockchain-certificates/cert-verifier-js/assets/78516163/daeab77a-546b-4c16-a390-a3d25d3447d6">

**Environment information:**
 - Node version: 18
 - OS: osx (apple silicon)

**Comment by wantaekchoi** [comment]
here is my code (nestjs):

```typescript
import { Injectable } from '@nestjs/common';
// import { Certificate } from '@blockcerts/cert-verifier-js';
const {
  Certificate,
} = require('@blockcerts/cert-verifier-js/dist/verifier-node.js');

@Injectable()
export class CertVerifierService {
  async verifyBlockerCertCertificate(certificateDefinition: string) {
    const certificate = new Certificate(certificateDefinition);
    await certificate.init();
    return certificate.verify();
  }
}
```

**Comment by wantaekchoi** [comment]
I have found my mistake. I missed the prefix in the hash value.

**Comment by lemoustachiste** [comment]
Did you fix the issue?

**Comment by wantaekchoi** [comment]
@lemoustachiste 
There were no issues. I confirmed that the error was caused by me using the wrong badge, so I closed the issue.

**Comment by wantaekchoi** [comment]
Good point!
The 404 response from Blockcypher was treated as a success because we got the correct response from Etherscan.

Although the question below is not appropriate for this issue,
Nevertheless, I was wondering if you could provide an additional answer for the explorer.
I want to apply just an my API key to the Etherscan API.
(I don't need my own parsing function, I want to use the existing etherScan's `parsingFunction`).
But it seems that defining a `parsingFunction` isn't optional.

Is there a good way to do this?

Translated with www.DeepL.com/Translator (free version)

**Comment by lemoustachiste** [comment]
Something like this should work:

```
const explorerAPI = {
        serviceName: 'etherscan',
        key: '[your-key]',
        keyPropertyName: 'apikey'
};
```

**Comment by wantaekchoi** [comment]
@lemoustachiste Thank you for your reply!
