### ISSUE TITLE
t.resolve is not a funtion

### ISSUE THREAD

**Issue by shubhampatel30** [blockchain-certificates/cert-verifier-js#18]
After adding "babal-polyfill" library for removing the regenertorRuntime error. it's giving the error t.resolve is not a function in the build/ployfill.js file.  Please response ASAP.

**Comment by raiseandfall** [comment]
Can you give us more details on configuration (node version) ?

**Comment by kimdhamilton** [comment]
I can't repro; some possibilities:
- Fixed with @raiseandfall's commit 94cc4604cfd7017dcece53ceb17a3a54c5004b7e. 
- Are dependencies and runtime configs correct -- also note mispelling of `babal` in your message?

Closing; please reopen with details if you're still running into this issue

**Comment by raiseandfall** [comment]
@kimdhamilton I believe this was fixed in my commit indeed.
