### ISSUE TITLE
README.md: API docs error `signatureImage`

### ISSUE THREAD

**Issue by davidlj95** [blockchain-certificates/cert-verifier-js#207]
The [README.md][readme] file states:

> - `signatureImage`: `String`. Raw data of the certificate's signature image;

While the source files [src/parser.js][parser] and [src/certificate.js][certificate] are indeed creating an array of [`SignatureImage`][signatureImageModel] objects that match the `SignatureLine` model from the Blockcerts standard.

Checked as when adding

```js
      console.log(certificate.signatureImage);
```

to [script-tag.html], it prints the array of [`SignatureImage`][signatureImageModel] objects.

I propose changing the API documentation in README.md to reflect the true type of the `signatureImage` field.

[readme]: https://github.com/blockchain-certificates/cert-verifier-js/blob/45875a5db1f3e26346dcff6e87606c6e035d0716/README.md
[parser]: https://github.com/blockchain-certificates/cert-verifier-js/blob/45875a5db1f3e26346dcff6e87606c6e035d0716/src/parser.js#L13-L43
[certificate]: https://github.com/blockchain-certificates/cert-verifier-js/blob/45875a5db1f3e26346dcff6e87606c6e035d0716/src/certificate.js#L117
[script-tag.html]: https://github.com/blockchain-certificates/cert-verifier-js/blob/45875a5db1f3e26346dcff6e87606c6e035d0716/test/e2e/script-tag.html
[signatureImageModel]: https://github.com/blockchain-certificates/cert-verifier-js/blob/45875a5db1f3e26346dcff6e87606c6e035d0716/src/models/signatureImage.js

**Comment by raiseandfall** [comment]
@davidlj95 Ah right good catch! Thank you
