### ISSUE TITLE
Naming scheme for blockchains

### ISSUE THREAD

**Issue by AnthonyRonning** [blockchain-certificates/cert-verifier-js#24]
In `default.js`, there's an enum for the blockchains and a string name:

```
  Blockchain: {
    bitcoin: "bitcoin",
    testnet: "testnet",
    regtest: "regtest",
    mocknet: "mocknet",
    ethmain: "ethmain",
    ethropst: "ethropst",
    ethtest: "ethtest"
  },
```

There's also:
```
  ChainSignatureValue: {
    /*
    These are the external display of `chain` in the signature suite. Adding a new type since `Blockchain` is
    used by the web component and so we need to remain compatible.
    */
    bitcoin: "bitcoinMainnet",
    testnet: "bitcoinTestnet",
    regtest: "bitcoinRegtest",
    ethmain: "ethereumMainnet",
    ethropst: "ethereumRopsten",
    ethtest: "ethereumTestnet",
    mocknet: "mockchain"
  },
```

I'm wondering if it makes sense to combine these or maybe use `ChainSignatureValue` strings for `Blockchain` as well? In order to provide a more easily parseable string for frontends? 

My main concern is with ethereum in this case. Maybe use `ethereum` for ethmain and `ropsten` for ethropst?

**Comment by AnthonyRonning** [comment]
I believe the `Blockchain` enum field is something that's just used for viewing a friendly name, so something like 

```
  Blockchain: {
    bitcoin: "Bitcoin",
    testnet: "Bitcoin Testnet",
    regtest: "Bitcoin Regtest",
    mocknet: "Mocknet",
    ethmain: "Ethereum",
    ethropst: "Ethereum Ropsten", 
    ethtest: "Ethereum Testnet"
  },
```

would be beneficial for web components and to simplify UI name parsing.

**Comment by lemoustachiste** [comment]
That's a valid point, I think we should add that to the v2 proposal.
I am not certain, but when instantiating a new Certificate we want to return the info that is currently given by `parseJSON`, so we would also send the `chain` and `chainAsHumanString` (maybe `chainCode` and `chainName`?). Anyway, maybe the structure of the object could be something along:
```
Blockchain: {
    bitcoin:  {
        code: "bitcoin",
        name: "Bitcoin"
    },
    ...
  }
```
 cc @raiseandfall

**Comment by raiseandfall** [comment]
I have two properties listed in the [v2 API proposal](https://github.com/blockchain-certificates/cert-verifier-js/issues/46#issue-342153716): `chain` for the chain code, and `chainAsString` for readable chain name.

**Comment by raiseandfall** [comment]
Done in v2. Closing.
