### ISSUE TITLE
Chain.so returns 503

### ISSUE THREAD

**Issue by yancyribbens** [blockchain-certificates/cert-verifier-js#263]
**Describe the bug**

`cert-verifier-js` defaults to `chain.so` to make api requests.  The behavior of `chain.so` has changed recently and is returning a 503 when the verifier attempts to validate a certificate.  This appears to be caused by Cloudflare "cloudflare i'm under attack mode" recently implemented by `chain.so`.

**To Reproduce**
1. clone this repo
2. create an empty page and set script source to `src='./dist/verifier-iife.js'`
3. run `new Verifier.Certificate(certificateDefinition)` using a valid blockcert;
4. 503 appears in javascript console:

`Failed to load resource: the server responded with a status of 503 ()`

**Expected behavior**

No 503 is expected

**Comment by lemoustachiste** [comment]
Hi @yancyribbens, indeed we noticed that this past week. Latest release should address the issue, so you can just update your project with v3.1.3.

**Comment by yancyribbens** [comment]
Hi @lemoustachiste.  I believe this bug is still present in master as well as tag `v3.1.3`

Here are the steps I tested:
1) `git checkout tags/v3.1.3`
2) `npm run build`
3) still receiving 503 when including `verifier-iife.js`

**Comment by lemoustachiste** [comment]
I followed your replication step and for me v3.1.3 works as expected.

<img width="527" alt="Screenshot 2019-08-20 at 17 39 35" src="https://user-images.githubusercontent.com/12797962/63362065-887b1800-c371-11e9-9d22-4bdad87cf4b7.png">

<img width="567" alt="Screenshot 2019-08-20 at 17 38 34" src="https://user-images.githubusercontent.com/12797962/63362100-929d1680-c371-11e9-89c9-3c012ac4cb7e.png">

<img width="542" alt="Screenshot 2019-08-20 at 17 40 43" src="https://user-images.githubusercontent.com/12797962/63362148-ac3e5e00-c371-11e9-8a37-390db417b17a.png">

If you are actually referring to the 503 response from chain.so - and not a verification issue -, this is beyond our control, and their response was that they were getting spammed a lot and chose to turn off the service until further notice. 

We would probably need to find a new chain explorer to augment the chance of verification success, but for now this is what we have.

**Comment by AnthonyRonning** [comment]
We should remove chain.so eventually, even if we do have fallbacks and the current code still verifies with blockcypher. Chain.so has said that they plan on bringing it back in the future, but as a paid API which won't be of use to us.

**Comment by yancyribbens** [comment]
I agree.  It seems like having an error message from Chain.so should be avoided in the console.

**Comment by AnthonyRonning** [comment]
@lemoustachiste mind if we reopen this ticket and maybe rename the title to something like "remove chain.so"?

**Comment by lemoustachiste** [comment]
y'all welcome to open a PR if you want too :)

**Comment by yancyribbens** [comment]
I think we should also add the ability to specify an independent self-hosted node instead of a trusted third party such as blockcyper, in case `blockcypher` decides to make changes similar to `chain.so`.  I will open a PR for this if I have the bandwidth to do so.

**Comment by raiseandfall** [comment]
Closing this, chain.so got removed in another PR.
