### ISSUE TITLE
Use Issuer Profile's RevocationList if missing from certificate

### ISSUE THREAD

**Issue by AnthonyRonning** [blockchain-certificates/cert-verifier-js#308]
**Describe the bug**

When `revocationList` is not present inside of the certificate, the verifier should check if it is included in the Issuer Profile and use that. Currently that is not happening, per https://github.com/blockchain-certificates/cert-verifier-js/blob/f8176c6f23309ea98c02c9577658c6def64ea0d5/src/verifier.js#L198

(note: `this.issuer` refers to `certificate.issuer` in this context`)

This is where the schema specifies that issuer's `revocationList` should be checked as a fallback: https://github.com/blockchain-certificates/cert-schema/blob/master/docs/issuer_schema-2.1.md#revocationlist 

**To Reproduce**
1. Go to blockcerts.org
2. In put this certificate, which does not have a `revocationList` property directly inside it: https://github.com/AnthonyRonning/https-github.com-labnol-files/blob/master/test/test-revocation.json
3. See that it passes verification (as a testnet cert)

**Expected behavior**

It should check the issuer profile (https://github.com/AnthonyRonning/https-github.com-labnol-files/blob/master/issuer-eth.json) to grab the revocationList property (https://github.com/AnthonyRonning/https-github.com-labnol-files/blob/master/revocation-eth.json) and fail verification due to revocation.

**Comment by guix77** [comment]
Hi,

I think I might be having the same issue on my community.blockcerts.org post: https://community.blockcerts.org/t/help-with-revocation/2411

1. This certificate should be revoked: https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/ethereum/ropsten/certificates/fictionaluniversity/Jane-Doe-Blockchain-for-developers-1.json 1
2. The revocation list is here and contains the certificate ID: https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/ethereum/ropsten/issuers/fictionaluniversity/revocation.json
3. The issuer profile is here: https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/ethereum/ropsten/issuers/fictionaluniversity/issuer.json

Another certificate that should be revoked is https://github.com/AnthonyRonning/https-github.com-labnol-files/blob/master/test/test-revocation.json

Both certificates do not contain a revocationList, but their corresponding issuer profile contain it and the certificates IDs are listed there.

**Comment by guix77** [comment]
@lemoustachiste @raiseandfall Any interest from your part to fix this? If not I would of course understand, we all have our priorities.

**Comment by lemoustachiste** [comment]
@guix77 sorry I only just saw your comment. Yeah it is in the pipes, but there were a couple of things to address first. I might be able to look at it deeper this week.

**Comment by lemoustachiste** [comment]
@guix77 so I investigated a bit and found a fix in the case of @AnthonyRonning's certificate.
However it didn't work for yours, so I looked up the data you shared.
The Blockcerts you provide has id `urn:uuid:76cbdfad-1f63-4a8e-9263-e623331c8dce`.
The revocationList bound to the issuer profile of this blockcerts is this one: https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/ethereum/ropsten/issuers/fictionaluniversity/revocation.json (which you link too in your issue), and the only revoked assertion listed is this id: `urn:uuid:be6c2ccd-0f9e-4e46-8b6d-a2f6b883e76a`, which does not match the Blockcert's one. 

Could you please confirm that the data is accurate? I am going to push the fix now.

**Comment by guix77** [comment]
@lemoustachiste No problemo, Julien :)

In the meantime, I forgot I had posted this certificate here and updated the file on GitHub with a new one...

So here is a new revocated certificate example now:

- certificate: https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/ethereum/ropsten/certificates/fictionaluniversity/Revocated%20example.json
- revocation: https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/ethereum/ropsten/issuers/fictionaluniversity/revocation.json
- issuer: https://raw.githubusercontent.com/guix77/blockcerts-certificates/master/ethereum/ropsten/issuers/fictionaluniversity/issuer.json

Thanks again :)

**Comment by lemoustachiste** [comment]
@guix77 the fix is in this PR. Feel free to comment on it, since it introduces a breaking change I am happy to hear the opinion of other consumers of the code: https://github.com/blockchain-certificates/cert-verifier-js/pull/475. I'm going to verify the blockcerts you provided.

**Comment by lemoustachiste** [comment]
Tested, it seems resolved by #475

**Comment by guix77** [comment]
Thanks @lemoustachiste !

I'm a little bit lost with your 3 options on #475 but I for this issue I'm having on v2, I can still add the revocation list in my certificates. For now at least. It would be nice to know quite soon before we issue MainNet certs.

**Comment by lemoustachiste** [comment]
It would keep the general principle the same, the only difference would come from how you initially instantiate your verification process.

Currently:
```
  const certificate = new Certificate(definition);
  const verification = await certificate.verify();
```

After the change (which will solve your issue):

```
  const certificate = new Certificate(definition);
  await certificate.init();
  const verification = await certificate.verify();
```

That regardless of the Blockcerts version you are following. Is that acceptable for your use case?

**Comment by guix77** [comment]
Sure! Thanks a lot!

**Comment by lemoustachiste** [comment]
https://github.com/blockchain-certificates/cert-verifier-js/releases/tag/v3.8.1 fixes this. It does not introduce the async change, so disregard my above comment.

**Comment by guix77** [comment]
Hi @lemoustachiste ! Sorry I didn't reply earlier, I didn't had the chance to test it yet. Revocation now works with out local revocation list URL in v3.8.1 !!! Thank you so much :)
