### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by guix77** [blockchain-certificates/cert-verifier-js#34]
There was no NPM package published, so I published it : https://www.npmjs.com/package/cert-verifier-js

Did you have a reason not to publish it ?

I can add you as maintainers anytime.

**Comment by raiseandfall** [comment]
This has been on our roadmap but we were waiting to have semver in place first. Can you add me (@raiseandfall) as maintainer? Thank you

**Comment by guix77** [comment]
Ah OK, great. I added raiseandfall on npmjs.com, I suppose it's you ?

Before publishing it, I didn't see that you were adding the Git repo with npm/yarn, sorry if that move was anticipated... We have 16 more hours yet to delete the NPM from the registry, do you want me to remove it?

**Comment by raiseandfall** [comment]
That's me indeed, thank you.
I think it's fine, we can let it in there. I'll create a `1.0.0` release on Github to be consistent with NPM. 

Merci pour le coup de main ;)
