### ISSUE TITLE
Error: Certificate.parseJson is not a function

### ISSUE THREAD

**Issue by minhanhnguyen2196** [blockchain-certificates/cert-verifier-js#41]
Hi, I'm trying to follow the instruction in the doc but get the error:  Certificate.parseJson is not a function.

var Certificate = require('cert-verifier-js');
var fs = require('fs');

fs.readFile('./sample.json', 'utf8', function (err, data) {
    if (err) {
      console.log(err);
    }
    console.log(data);
    let cert = Certificate.parseJson(JSON.parse(data));
    console.log(cert.name);
  });

Need some help.

**Comment by lemoustachiste** [comment]
From this perspective it seems correct, but I am new to the code. Have you tried looking at what is your `Certificate` in a console.log? I think it might not be exactly what you expect it to be, hence why `parseJson` is not a function.

**Comment by minhanhnguyen2196** [comment]
Thanks, I made a few changes and it worked. 

var verifier = require ('cert-verifier-js');
var fs = require('fs');

fs.readFile('./sample.json', 'utf8', function (err, data) {
    if (err) {
      console.log(err);
    }
    let cert = verifier.Certificate.parseJson(JSON.parse(data));
    console.log(cert.name);
  });
