### ISSUE TITLE
Serious: Etherscan rate limits now prevent ANY unmodified cert-verifier-js implementations from validating

### ISSUE THREAD

**Issue by akodate** [blockchain-certificates/cert-verifier-js#422]
Hi guys,

As you may be aware, [etherscan has begun requiring API keys as of Feb. 15—yesterday](https://medium.com/etherscan-blog/psa-for-developers-implementation-of-api-key-requirements-starting-from-february-15th-2020-b616870f3746).
This prevents ANY unmodified cert-verifier-js implementations—including blockcerts-verifier implementations and [blockcerts.org](https://www.blockcerts.org/)(!!)—from validating Ethereum-based blockcerts (showing the "transaction occurred when issuing address wasn't valid" error).

Having broken verifiers all over the internet is a bad look for the Blockcerts ecosystem; so maybe a simple solution would benefit everyone.

My suggestion would be to allow people to pass their api key into cert-verifier-js, with api.js Line 30~ looking something like this:
```
  [TRANSACTION_APIS.Etherscan]: {
    main: `https://api.etherscan.io/api?module=proxy&apikey=${ETHERSCAN_API_KEY}`,
    ropsten: `https://api-ropsten.etherscan.io/api?module=proxy&apikey=${ETHERSCAN_API_KEY}`
  }
```

Then (ideally) I would allow that api key to be passed through blockcerts-verifier as a prop to cert-verifier-js.

I would love to help with this more directly but I haven't been able to easily build cert-verifier-js on my machine.

EDIT: Even though the api key is free, exposing it definitely isn't ideal. But it seems like it may be necessary as a stopgap measure/way for new users to get the verifier working until a more permanent solution can be devised. 

Thoughts?

**Comment by AnthonyRonning** [comment]
Thank you very much @akodate for raising the issue so promptly. 

Yes, not an ideal approach but you're exactly right, a great quick solution, thanks for the code snippets.

We just merged into CVJS and will get this fix propagated to blockcerts.org and the mobile apps asap. We have backup API's for bitcoin so it's less of a concern if one goes down but not at this moment for ethereum.

**Comment by akodate** [comment]
And thank you @AnthonyRonning for handling this swiftly on a Sunday. I'll test it out when blockcerts-verifier is updated.

**Comment by AnthonyRonning** [comment]
@akodate , blockcerts-verifier has been updated, it's live in blockcerts.org and we are working on the mobile apps now. Closing this ticket for now, thanks again!
