### ISSUE TITLE
Improve Ethereum APIs support

### ISSUE THREAD

**Issue by raiseandfall** [blockchain-certificates/cert-verifier-js#425]
- address the current Ethscan configuration: the API key is hardcoded in the constants, which works but is no ideal
- implement more Ethereum APIs

**Comment by AnthonyRonning** [comment]
MyEtherWallet might be a good one to add, we did that over in the cert-issuer: https://github.com/blockchain-certificates/cert-issuer/blob/master/cert_issuer/blockchain_handlers/ethereum/connectors.py#L148

**Comment by lemoustachiste** [comment]
done in #546
