### ISSUE TITLE
After upgrading to any version greater than 3.2.1, importing package in nextjs app setup results in "Error compiling schema" error

### ISSUE THREAD

**Issue by SamHellawell** [blockchain-certificates/cert-verifier-js#429]
We have been using the verifier package for some time on older versions, but after we realized that we need to upgrade to due api key requirement now we noticed that all later versions other than 3.2.1 do not seem to transpile properly. Here is the error I get when importing the package:

Import via:
```import {Certificate} from '@blockcerts/cert-verifier-js';```

Results in:
```index.js:1 Error compiling schema, function code: var refVal1 = refVal[1]; var validate = function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;  var errors = 0;            var errs_1 = errors;    var errs_2 = errors; if ((typeof data !== "number" || (data % 1) || data !== data)) {  validate.errors = [ { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/type' , params: { type: 'integer' }  , message: 'should be integer'  } ]; return false;  }  if (typeof data === "number") {    if (  data < 0 || data !== data) {  validate.errors = [ { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/minimum' , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' } ]; return false;  }    }    var valid2 = errors === errs_2;     var valid1 = errors === errs_1;      validate.errors = vErrors;  return errors === 0;        }; return validate;```

I figured it may be an issue with babel config or node versions, so I tried to update that to be like what is in this repo. Still no luck. Here is current babel config:

```module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
  overrides: [
    {
      test: ['./src'],
      presets: ['next/babel'],
      plugins: [['styled-components', {ssr: true}]],
    },
  ],
};
```

Something changed in version v3.3.0 that is causing this issue. Any insight would be appreciated.

**Comment by AnthonyRonning** [comment]
How about v3.3.3 or v3.4.0?

**Comment by lemoustachiste** [comment]
Hi @SamHellawell,

the error in this index.js, is this the code of your project? And when do you get this error? At build time or run time?

I have noticed that we are having troubles with blockcerts-verifier with the most recent builds (like you said from 3.3.0). I think the issue has to do with an update of jsonld, but I haven't been able to pinpoint why exactly, and how to fix it.

I think you could have luck using v3.3.3 for now, as we had temporarily rolled back jsonld to 0.4.1. This would enable the API keys for ETH but also potentially not break things.

**Comment by SamHellawell** [comment]
Thanks for the quick response. We are using NextJS, index.js is a bunch of transpiled ES6 to run in a React environment. Here is the full stack incase useful.

```console.<computed> @ index.js:1
w @ verifier-es.js:1
ro @ verifier-es.js:1
_ @ verifier-es.js:1
$ref @ verifier-es.js:1
bo @ verifier-es.js:1
properties @ verifier-es.js:1
bo @ verifier-es.js:1
w @ verifier-es.js:1
e @ verifier-es.js:1
push.../../node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js.Na._compile @ verifier-es.js:1
push.../../node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js.Na.getSchema @ verifier-es.js:1
(anonymous) @ verifier-es.js:1
push.../../node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js.Na.validateSchema @ verifier-es.js:1
push.../../node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js.Na._addSchema @ verifier-es.js:1
push.../../node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js.Na.compile @ verifier-es.js:1
(anonymous) @ verifier-es.js:1
../../node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js @ verifier-es.js:97
__webpack_require__ @ bootstrap:797
fn @ bootstrap:150
../shared/modules/wallet/credential-details/blockcerts/sidebar-verifier.js @ blockcert-verifier-modal.js:44
__webpack_require__ @ bootstrap:797
fn @ bootstrap:150
Promise.then (async)
loader @ blockcerts.js:19
load @ loadable.js:35
retry @ loadable.js:187
LoadableSubscription @ loadable.js:180
init @ loadable.js:114
LoadableComponent @ loadable.js:142
renderWithHooks @ react-dom.development.js:16260
updateForwardRef @ react-dom.development.js:18143
beginWork$1 @ react-dom.development.js:20211
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24698
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
scheduleUpdateOnFiber @ react-dom.development.js:23709
dispatchAction @ react-dom.development.js:17076
(anonymous) @ modal.provider.js:56
setTimeout (async)
showModal @ modal.provider.js:55
handleCertClick$ @ table.js:140
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
tryCatch @ runtime.js:45
invoke @ runtime.js:135
(anonymous) @ runtime.js:145
Promise.then (async)
invoke @ runtime.js:144
(anonymous) @ runtime.js:170
callInvokeWithMethodAndArg @ runtime.js:169
enqueue @ runtime.js:192
prototype.<computed> @ runtime.js:97
push.../../node_modules/regenerator-runtime/runtime.js.exports.async @ runtime.js:216
handleCertClick @ table.js:136
onClick @ credential-item.js:28
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:454
executeDispatch @ react-dom.development.js:584
executeDispatchesInOrder @ react-dom.development.js:609
executeDispatchesAndRelease @ react-dom.development.js:713
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:722
forEachAccumulated @ react-dom.development.js:694
runEventsInBatch @ react-dom.development.js:739
runExtractedPluginEventsInBatch @ react-dom.development.js:880
handleTopLevel @ react-dom.development.js:5803
batchedEventUpdates$1 @ react-dom.development.js:24401
batchedEventUpdates @ react-dom.development.js:1415
dispatchEventForPluginEventSystem @ react-dom.development.js:5894
attemptToDispatchEvent @ react-dom.development.js:6010
dispatchEvent @ react-dom.development.js:5914
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
discreteUpdates$1 @ react-dom.development.js:24417
discreteUpdates @ react-dom.development.js:1438
dispatchDiscreteEvent @ react-dom.development.js:5881
```

Happens in development and production modes. v3.3.3 results in the same issue, as does v3.4.0. Im sure its related to the dev setup we have, but hard to pin point what exactly. Tried down/upgrading babel and node, other related packages, matching babel configs etc. Works perfect at 3.2.1.

**Comment by lemoustachiste** [comment]
Can you try with 3.3.2, just to rule out the issue?
I'll try and dive into it too.
We are using rollup in Blockcerts Verifier, and what we have as an error there is an issue with terser and `contains_this` method (I think coming from uglifyjs), only at build time.

Also what you could try to help identify your error is cloning this repo, make a npm link of it in your project and then in your copy of the repo disable terser in the rollup config and run `npm run build`. Then in your project, do the same steps you do when you get this error and we might see which line (and potentially package) brings the error up. Or if you want to make a repro, I can also investigate myself.

Sorry about that.

**Comment by SamHellawell** [comment]
Same issue with 3.3.2.

Interesting you mentioned Terser and the contains_this error, we also have another project using Gatsby providing a verify tool - and when running in development mode 3.4.0 works (and all others). However at build time, there was that error and similar such as:

```Error: 30-c474cd61975a14f62f14.js from Terser
  undefined```

So pretty sure Terser is at fault here somewhere. I'll fork this repo and play around with settings/compilation options. I did read here (https://github.com/webpack-contrib/terser-webpack-plugin/issues/119) that upgrading Terser resolved it. Maybe its just a matter of upgrading rollup terser package for this lib?

**Comment by lemoustachiste** [comment]
@SamHellawell could you try with the latest version released?

**Comment by lemoustachiste** [comment]
Hi @SamHellawell,

I am closing this since no updates on your side.
