### ISSUE TITLE
[WIP] API v2 design proposal 

### ISSUE THREAD

**Issue by raiseandfall** [blockchain-certificates/cert-verifier-js#46]
# Goals
- update API design to reflect the verification steps update
- simplify the current API: `Certificate.parseJson()` is called twice: once by the consumer to parse the certificate and get its descriptive object, and a second time [inside the verification function](https://github.com/blockchain-certificates/cert-verifier-js/blob/master/lib/verifier.js#L31)
- introduce an easier way for a consumer app to know if a certificate has a valid format or not
- ...

# Contribution
This is a shared effort, any suggestion is most welcomed.

# Proposal

## Usage
```javascript
import Certificate from 'cert-verifier-js'; 
const certificate = new Certificate(certificateContentString);
```

### `constructor(certificateContentString)`
```javascript
const certificate = new Certificate(certificateContentString);
```
The constructor automatically parses a certificate.

#### Parameter
`certificateContentString`: `String`. certificate raw content

#### Instance
The certificate instance has the following properties:
- `isFormatValid`: `Boolean`. Indicates whether or not the certificate has a valid format
- `certificateImage`: `String`. Raw data of the certificate image
- `chain`: `Object`. Chain the certificate was issued on
- `description`: `String`. Description of the certificate
- `expires`: `String`. Expiration date
- `id`: `String`. Certificate's ID
- `issuer`: `Object`. Certificate issuer
- `publicKey`: `String`. Certificate's public key
- `rawTransactionLink`: `String`. Raw transaction ID
- `receipt`: `String`. Certificate's receipt
- `recipientFullName`: `String`. Full name of recipient
- `revocationKey`: `String|null`. Revocation key (if any)
- `sealImage`: `String`. Raw data of the seal's image;
- `signature`: `String`. Certificate's signature
- `signatureImage`: `String`. Raw data of the certificate's signature image;
- `subtitle`: `String`. Subtitle of the certificate
- `name`: `String`. Name of the certificate
- `transactionId`: `String`. Transaction ID
- `transactionLink`: `String`. Transaction link
- `verificationSteps`: `VerificationStep[]`. The array of steps the certificate will have to go through during verification
- `version`: `CertificateVersion`. [Version of the certificate](https://github.com/blockchain-certificates/cert-verifier-js/blob/v2-wip/config/default.js#L60)

**Note:** `verificationSteps` is generated according to the nature of the certificate. The full steps array is provided ahead of verification in order to give more flexibility to the consumer. For example, the consumer might want to pre-render the verification steps for animation, or render a count of steps and/or sub-steps.

A `VerificationStep` has the following shape:
```javascript
{
    code: `stepCode`,
    name: `Readable Step Name`,
    status: `success`,
    substeps: [
        {
            code: `subStepCode`,
            name: `Readable Sub Step Name`,
            status: `success`,
            parentStep: `stepCode`
        },
        ...
    ]
}
```

### `verify(stepCallback)`
The function is asynchronous.
```javascript
const certificateVerification = await certificate.verify(({code, name, status, errorMessage}) => {
    console.log('Sub step update:', name, status);
}));
console.log(`Verification was a ${certificateVerification.status}:`, certificateVerification.errorMessage);
```
#### Parameter
`({code, name, status, errorMessage}) => {}`: `Function`. Callback function called whenever a substep status has changed. The callback parameter has 4 properties: 
- `code`: substep code
- `name`: readable name of the substep
- `status`: substep status (`success`, `failure`, `starting`)
- `errorMessage`: error message (optional)

#### Returns
The final verification status:
```javascript
{ status, errorMessage }
```
- `status`: final verification status (`success`, `failure`)
- `errorMessage`: error message (optional)

**Comment by lemoustachiste** [comment]
It feels simpler indeed. The only thing I think is that the `new Certificate` constructor should also return the initial certificate definition object, so that we can manipulate only one item throughout?

In the new implementation of the verifier I have to have 2 ways to handle both these pieces of information to reconcile them at a later point, I think it could remove one step then. But that's the only use case I know.

Otherwise I agree with the proposal.

@guix77 you seem to be using this library too, do you have anything you'd like to add?

**Comment by guix77** [comment]
@lemoustachiste thanks for asking :)

I have little time to invest but I read the proposal and your remarks, it all sounds fine to me.

For the format validation, it would be nice not to be too restrictive in order to allow extra properties of the object, like of course custom fields.

I like the sub steps callback feature :)

**Comment by raiseandfall** [comment]
@lemoustachiste @guix77 @tadityar 
Hi guys,

I wanted to give you a heads up: we are about to release the `v2` on NPM in the next coming days. This version has breaking changes from the `v1`. 
To keep using the `v1` you'll have to update the dependency source in your package.json:
Replace
```json
"cert-verifier-js": "git@github.com:blockchain-certificates/cert-verifier-js.git"
```
By
```json
"cert-verifier-js": "^1.0.0"
```
Please disregard this message if you were already using the library as a npm package.

Thank you!
Matthieu
