### ISSUE TITLE
Retrieve issuer profile when issuer key is a URL

### ISSUE THREAD

**Issue by lemoustachiste** [blockchain-certificates/cert-verifier-js#468]
It can happen that the `issuer` key is a [string](https://github.com/blockchain-certificates/cert-verifier-js/blob/master/test/fixtures/blockcerts-3.0-alpha.json#L12) (most likely a URL). If such is the case, as the `issuer` data is not stored in the certificate definition, the Certificate constructor [will return just the URL](https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/parsers/parseV3.js#L17) of the issuer profile.

It would feel like an adequate responsibility to actually fetch the distant profile and populate the `Certificate.issuer` with the distant data.

**Comment by guix77** [comment]
I can't understand the problem here. It seems to me that the Blockcerts v2 standard requires `issuer` to follow its JSON schema, which requires a lot more than just a string. Why would this library accept exceptions to the schema?

**Comment by lemoustachiste** [comment]
done in #475 
@guix77 sorry again your comment slipped my radar. Moving to Verifiable Credentials for Blockcerts V3 this becomes true.
