### ISSUE TITLE
Allow list of custom blockchain explorers

### ISSUE THREAD

**Issue by lemoustachiste** [blockchain-certificates/cert-verifier-js#471]
CVJS should accept a custom list of explorers
This data could be passed as follow:
```
[
  {
     serviceUrl: string,
     key: string,
     priority: number: 0 | 1 // if it's 0 it means it gets executed before the free APIs listed in CVJS, 1 after.
  } 
]
```

It seems it is not a concern of the Certificate itself, so this would more likely be pertinent to be sent into the verify method of the certificate object.

One concern that remains is the parsing of the response, an ideal solution would be generic for most or all cases. In practice the API response is likely to be specific per explorer service and difficult to generalize.

This means, do we need to allow the parsing function to be sent along for each explorer? This might prove complicated when consuming from Blockcerts Verifier. More exploration needed.

**Comment by guix77** [comment]
In my opinion, ideally cert-verifier-js could provide by default 1 or more blockchain services for Bitcoin and Ethereum as an implementation of a generic interface that could allow any other situation, up to injected wallet managers such as Metamask.

But that's a lot of work...

**Comment by lemoustachiste** [comment]
updated model:

```
{
    serviceAPIs: [{
        serviceUrl: string | { mainnet: string, testnet: string },
        priority: number (0, 1),
        parsingFunction: Function
    }]
}
```
If `serviceUrl` is a string, then it's assumed it is a mainnet API. We also realized that the key is often part of the url so we could remove the need for passing it independently. The parsing function is the one that should return the `txData` from the response of the API.

**Comment by raiseandfall** [comment]
@lemoustachiste I'd like to propose the following names for the serviceUrls (`main` and `test`):
```
{
    serviceAPIs: [{
        serviceUrl: string | { main: string, test: string },
        priority: number (0, 1),
        parsingFunction: Function
    }]
}
```

I have an example in the single explorer refactor PR: https://github.com/blockchain-certificates/cert-verifier-js/commit/99da58b22b091b3bcca5cc998c012d7a07b2ef32#diff-b043045ce92ff1bae617848eb2640756R27-R30
Let me know what you think.

**Comment by lemoustachiste** [comment]
done
