### ISSUE TITLE
Change to chain.so for verifying transaction id

### ISSUE THREAD

**Issue by ktrev** [blockchain-certificates/cert-verifier-js#58]
verifier.js is checking in api.blockcypher.com for the transaction id. 
But this API is showing that the transaction id does not exist.
https://api.blockcypher.com/v1/btc/test3/txs/52cbb934e0803ce7b26a98e669a25136221efaca4f65565da18d842e57e52f69?limit=500

But the same transaction is appearing in chain.so
https://chain.so/api/v2/get_tx/BTCTEST/52cbb934e0803ce7b26a98e669a25136221efaca4f65565da18d842e57e52f69

Have noticed many times that this happens with blockcypher (i don't know the reason though). So we would like to switch to chain.so for checking transaction id. Please let us know how to proceed on this.

**Comment by raiseandfall** [comment]
Closing, we've updated the list of APIs used for verification. Chain.so is not supported anymore
