### ISSUE TITLE
Add the ability to specify custom chain

### ISSUE THREAD

**Issue by crossoveranx** [blockchain-certificates/cert-verifier-js#664]
Currently, this repository has a few different options for support chains - but many other ethereum sidechains would be interested in using the blockcerts infrastructure for verifiable credentials. I recommend adding the ability to pass a custom RPC in order to look up transactions on other chains.

**Comment by lemoustachiste** [comment]
I am wondering if you could use the custom `explorerAPIs` function to do so? I have not done it myself but it hit me the other that it could work.

**Comment by lemoustachiste** [comment]
@crossoveranx so I have done more research on that subject, and it is currently not possible to lookup for a custom chain, other than BTC or ETH. 

I have made some changes on this library that will allow to do so: https://github.com/blockchain-certificates/jsonld-signatures-merkleproof2019/pull/8. I will want to port these changes to CVJS, but it will take some time as I don't have much leeway in the coming 2 months. For all intent and purposes, what chain were you interested in bringing in? Does it comply with RPCs?

**Comment by lemoustachiste** [comment]
Hi @crossoveranx,

it is now possible to look up non natively supported chains. Documentation for it at this point is here: https://github.com/blockchain-certificates/jsonld-signatures-merkleproof2019#under-the-hood
