### ISSUE TITLE
keyPropertyName/key pair is not appended to the URL querystring on verify again

### ISSUE THREAD

**Issue by raiseandfall** [blockchain-certificates/cert-verifier-js#667]
When passing a custom `explorerAPI` with a set of `keyPropertyName` & `key` for a specific `serviceName`, the key value pair (`&|?keyPropertyName=key`) is only applied on the first verification flow.

**Comment by supergillis** [comment]
@raiseandfall 

Is it possible that this PR breaks setting a custom `parsingFunction` in `explorerAPIs`? `deepCopy` does not copy the function.
