### ISSUE TITLE
BTC testnet validations fail due to out-of-date URL

### ISSUE THREAD

**Issue by lparkerlm** [blockchain-certificates/cert-verifier-js#689]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: try to validate a testnet certficate.

**Expected behavior**

A call to blockchain.com/btc-testnet.

**Screenshots**

A call, instead, to the old testnet.blockchain.info.

![image](https://user-images.githubusercontent.com/35699884/90587977-676d2300-e18f-11ea-811c-ea7bd27424d4.png)

**Comment by lemoustachiste** [comment]
That is happening with v2 right? I'll take a look

**Comment by lparkerlm** [comment]
No repro on this - might have been a caching issue on my side.
