### ISSUE TITLE
Cert Verifier with external explorer APIs - Issue

### ISSUE THREAD

**Issue by danishfastian** [blockchain-certificates/cert-verifier-js#846]
As per my below post I am getting below error when trying to use external API

https://community.blockcerts.org/t/cert-verifier-with-external-explorer-apis/2711

Some observations based on debugging:
==========================
1. Deep copy in at line 102 of certificate.ts is probably responsible for removing function ref: https://medium.com/javascript-in-plain-english/deep-clone-an-object-and-preserve-its-type-with-typescript-d488c35e5574
It is converting to same code i.e. JSON.parse(JSON.stringify(e)
2. Also in isParsingFunctionValid in ensureValidity.ts, an array of explorerapi is passed but validation expect it is not array 

Using below code gives error "One or more of your custom explorer APIs does not have a parsing function"

var myOptions = {
                explorerAPIs:
                [
                    {
                        serviceName: "BlockCypherTest",
                        parsingFunction: function (e) {
                            if (e.confirmations < mr) throw new Yn(Gt, mn("errors", "parseBlockCypherResponse"));
                            const t = Qf(e.received), r = e.outputs, n = r[r.length - 1], i = e.inputs[0].addresses[0];
                            return { remoteHash: oN(n.script, hr.bitcoin.prefixes), issuingAddress: i, time: t, revokedAddresses: r.filter(e => !!e.spent_by).map(e => e.addresses[0]) }
                        },
                        priority: 1,
                        serviceURL:
                        {
                            main: "https://api.blockcypher.com/v1/btc/main/txs/{transaction_id}?limit=500",
                            test: "https://api.blockcypher.com/v1/btc/test3/txs/{transaction_id}?limit=500"
                        }
                    }
                ] 
            };    

            const certificate = new Verifier.Certificate(this.certJSON, myOptions);

**Comment by supergillis** [comment]
I bumped into the same issue a couple of days ago. Left a comment on the PR that introduced this issue https://github.com/blockchain-certificates/cert-verifier-js/issues/667

**Comment by raiseandfall** [comment]
Hi @danishfastian @supergillis

Thank you for reporting these issues. I didn't have a change to look into it until now. I hope to be able to provide a fix & answer later today.

**Comment by lemoustachiste** [comment]
fixed by v4.5.1

**Comment by supergillis** [comment]
Thanks. Could you by any chance also cut a new release for `@blockcerts/blockcerts-verifier` using the fixed version of `@blockcerts/cert-verifier-js`?

**Comment by raiseandfall** [comment]
@supergillis [1.34.1](https://github.com/blockchain-certificates/blockcerts-verifier/releases/tag/v1.34.1) has it.
